const curriculumData = {
    "Grade 6": [
        { week: 1, topic: "Digital Literacy", description: "Basics of the internet and safety", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["Online safety"], task: "Identify 3 phising signs." },
        { week: 2, topic: "Intro to Algorithms", description: "Step-by-step problem solving", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["Logical thinking"], task: "Write a PB&J algorithm." },
        { week: 3, topic: "Block Coding 1", description: "Visual programming fundamentals", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Visual logic"], task: "Make a character move." },
        { week: 4, topic: "Variables in Blocks", description: "Storing data in visual code", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Data storage"], task: "Create a score counter." },
        { week: 5, topic: "Digital Citizenship", description: "Respectful online interaction", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["Netiquette"], task: "Draft a netiquette guide." },
        { week: 6, topic: "Loops in Blocks", description: "Repeating actions efficiently", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Iteration"], task: "Draw a square." },
        { week: 7, topic: "Conditionals", description: "Making decisions in code", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Logic gates"], task: "Build a maze gate." },
        { week: 8, topic: "Events & Triggers", description: "Responding to user input", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Interactivity"], task: "Click-to-play game." },
        { week: 9, topic: "Debugging Basics", description: "Finding and fixing errors", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Persistence"], task: "Fix a broken script." },
        { week: 10, topic: "Game Design Intro", description: "Core elements of fun games", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["Design thinking"], task: "Map out a game idea." },
        { week: 11, topic: "Data Privacy", description: "Protecting personal info online", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["Privacy awareness"], task: "Check privacy settings." },
        { week: 12, topic: "Block Functions", description: "Reusable code blocks", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Modularity"], task: "Create a 'dance' function." },
        { week: 13, topic: "Internet Infrastructure", description: "How routers and cables work", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["Networking"], task: "Label a network diagram." },
        { week: 14, topic: "Simple Animations", description: "Bringing characters to life", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Creative tech"], task: "Animate a walking sprite." },
        { week: 15, topic: "Hardware Basics", description: "Understanding CPU, RAM, and Disk", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["Hardware literacy"], task: "List PC components." },
        { week: 16, topic: "Variables Deep Dive", description: "Math and strings in blocks", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Math in code"], task: "Build a calculator." },
        { week: 17, topic: "Lists & Arrays", description: "Handling multiple items", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Collections"], task: "Make a grocery list app." },
        { week: 18, topic: "AI Fundamentals", description: "What is AI and how it learns", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["AI literacy"], task: "Spot AI in daily life." },
        { week: 19, topic: "Machine Learning intro", description: "Training a simple model", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Model training"], task: "Teach AI to recognize cats." },
        { week: 20, topic: "Robotics Intro", description: "Sensors, actuators, and code", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["Robotics basics"], task: "Draw a robot assistant." },
        { week: 21, topic: "Creative Project Phase 1", description: "Defining project goals", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Planning"], task: "Draft project proposal." },
        { week: 22, topic: "Introduction to Circuits", description: "Basics of electricity and circuits", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["Electronics basics"], task: "Draw a simple circuit." },
        { week: 23, topic: "LED Control with Python", description: "Making things blink with code", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Physical computing"], task: "Program an LED flash." },
        { week: 24, topic: "Sound Sensors", description: "How computers hear the world", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Sensor tech"], task: "Measure clap volume." },
        { week: 25, topic: "Light Sensors", description: "Detecting brightness with code", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Environmental sensing"], task: "Build a sun detector." },
        { week: 26, topic: "Building a Night Light", description: "A simple smart device project", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Applied logic"], task: "LED on when it's dark." },
        { week: 27, topic: "Intro to AI Vision", description: "How computers see images", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["Computer vision"], task: "Label objects in a photo." },
        { week: 28, topic: "Emotion Recognition basics", description: "AI reading facial expressions", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["AI ethics"], task: "Test a smile detector." },
        { week: 29, topic: "AI Chatbot basics", description: "Talking to machines", type: "Theory", duration: "45 mins", level: "Beginner", outcomes: ["NLP basics"], task: "Draft chatbot responses." },
        { week: 30, topic: "Project Planning", description: "Structuring your final work", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Project management"], task: "Create a Trello board." },
        { week: 31, topic: "Data Collection for Project", description: "Gathering what you need", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Research"], task: "Survey 10 classmates." },
        { week: 32, topic: "Building Prototype (Part 1)", description: "Starting the construction", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Development"], task: "Code the core logic." },
        { week: 33, topic: "Building Prototype (Part 2)", description: "Refining the build", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Iteration"], task: "Add the user interface." },
        { week: 34, topic: "Testing & Debugging", description: "Ensuring everything works", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["QA"], task: "Fix 3 bugs found." },
        { week: 35, topic: "Final Refinement", description: "Polishing for the presentation", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Presentation prep"], task: "Polish the UI/UX." },
        { week: 36, topic: "Capstone Showcase", description: "Final presentation of projects", type: "Practical", duration: "45 mins", level: "Beginner", outcomes: ["Public speaking"], task: "Present your project." }
    ],
    "Grade 7": [
        { week: 1, topic: "Python Intro", description: "Setting up and printing hello", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Python setup"], task: "Install Python & print name." },
        { week: 2, topic: "Vars & Types", description: "Strings, ints, and floats", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Data types"], task: "Calc age in days." },
        { week: 3, topic: "List Ops", description: "Adding and removing from lists", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["List manipulation"], task: "Manage a guest list." },
        { week: 4, topic: "Math Module", description: "Using Python's math library", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Library usage"], task: "Calculate circle area." },
        { week: 5, topic: "Input Handling", description: "Getting user data safely", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["User interaction"], task: "Build a mad libs game." },
        { week: 6, topic: "Control Flow", description: "If/Else logic in Python", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Python logic"], task: "Build a grade checker." },
        { week: 7, topic: "Nested Ifs", description: "Complex decision trees", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Decision making"], task: "Create an RPG choice menu." },
        { week: 8, topic: "Logic Operators", description: "AND, OR, NOT in code", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Boolean logic"], task: "Login system validator." },
        { week: 9, topic: "Python Functions", description: "Defining and calling functions", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Code reuse"], task: "Create a currency converter." },
        { week: 10, topic: "Python Loops", description: "Automating repeated tasks using code", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Python repetition"], task: "Build a digital counter.",
            resources: { ppt: "#", pdf: "#", video: "#" }, tools: ["Deepseek", "Claude"], weight: { theory: 20, practical: 80 }
        },
        { week: 11, topic: "Sensor Data Concept", description: "Understanding how sensors collect environment data", type: "Theory", duration: "45 mins", level: "Intermediate", outcomes: ["Data acquisition"], task: "List sensor types." },
        { week: 12, topic: "Scope & Variables", description: "Global vs Local variables", type: "Theory", duration: "45 mins", level: "Intermediate", outcomes: ["Memory management"], task: "Fix scope errors." },
        { week: 13, topic: "Error Handling", description: "Try/Except blocks", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Robust code"], task: "Handle div by zero." },
        { week: 14, topic: "File I/O Basics", description: "Reading from text files", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Persistent data"], task: "Read a config file." },
        { week: 15, topic: "Writing to Files", description: "Saving data to disk", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Data storage"], task: "Save game scores." },
        { week: 16, topic: "Dictionaries", description: "Key-value pairs in Python", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Hash maps"], task: "Build a phonebook app." },
        { week: 17, topic: "IoT Hardware Intro", description: "Microcontrollers and Wiring", type: "Theory", duration: "45 mins", level: "Intermediate", outcomes: ["Electrical basics"], task: "Design a circuit diagram." },
        { week: 18, topic: "Digital Writing", description: "Controlling pins with Python", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["GPIO control"], task: "Morse code blinker." },
        { week: 19, topic: "Digital Reading", description: "Detecting button presses", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Input sensing"], task: "Toggle light with button." },
        { week: 20, topic: "Analog Inputs", description: "Reading variable voltages", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["ADC conversion"], task: "Read a potentiometer." },
        { week: 21, topic: "Cloud Connectivity (IoT)", description: "Connecting devices to the web", type: "Theory", duration: "45 mins", level: "Intermediate", outcomes: ["Cloud basics"], task: "Sketch a cloud-IoT map." },
        { week: 22, topic: "API Basics", description: "How apps talk to each other", type: "Theory", duration: "45 mins", level: "Intermediate", outcomes: ["Web services"], task: "Find 3 public APIs." },
        { week: 23, topic: "Weather API Project", description: "Getting real-time data", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["API consumption"], task: "Fetch weather for city." },
        { week: 24, topic: "Smart Home Simulation", description: "Automating light based on time", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["System automation"], task: "Code a 'Good Morning' routine." },
        { week: 25, topic: "ML Model Training basics", description: "How computers learn from data", type: "Theory", duration: "45 mins", level: "Intermediate", outcomes: ["ML lifecycle"], task: "Define 'training set'." },
        { week: 26, topic: "Supervised Learning concept", description: "Learning with labels", type: "Theory", duration: "45 mins", level: "Intermediate", outcomes: ["Classification"], task: "Label a dataset." },
        { week: 27, topic: "Classification Project", description: "Building a simple classifier", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Applied ML"], task: "Sort spam emails." },
        { week: 28, topic: "Data Visualization intro", description: "Drawing graphs with Python", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Matplotlib basics"], task: "Plot a line graph." },
        { week: 29, topic: "Dashboard Design", description: "Creating simple UI for data", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["UX/UI basics"], task: "Sketch a data dashboard." },
        { week: 30, topic: "Capstone Ideation", description: "Brainstorming for the big project", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Problem solving"], task: "Submit 3 project ideas." },
        { week: 31, topic: "Prototype Design", description: "Wireframing your project", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Design thinking"], task: "Draw your project UI." },
        { week: 32, topic: "Hardware Integration", description: "Connecting sensors to logic", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["System design"], task: "Draft hardware list." },
        { week: 33, topic: "Backend Logic", description: "Core processing for project", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Logic development"], task: "Write the main loop." },
        { week: 34, topic: "Security for IoT", description: "Keeping devices safe from hacks", type: "Theory", duration: "45 mins", level: "Intermediate", outcomes: ["Cybersecurity"], task: "List 5 security risks." },
        { week: 35, topic: "Project Testing", description: "Vandalizing your own code to fix it", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["QA/Testing"], task: "Perform a 'crash test'." },
        { week: 36, topic: "Graduation Demo Day", description: "Final presentation of Grade 7 work", type: "Practical", duration: "45 mins", level: "Intermediate", outcomes: ["Communication"], task: "Showcase your project." }
    ],
    "Grade 8": [
        { week: 1, topic: "Classes & Objects", description: "OOP fundamentals in Python", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["OOP basics"], task: "Create a Dog class." },
        { week: 2, topic: "Inheritance", description: "Creating subclasses and hierarchy", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["OOP inheritance"], task: "Build a Vehicle system." },
        { week: 3, topic: "Data Structures", description: "Stacks, Queues, and Trees", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["CS fundamentals"], task: "Draw a binary tree." },
        { week: 4, topic: "Recursion", description: "Functions that call themselves", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Algorithmic thinking"], task: "Calc Factorial recursively." },
        { week: 5, topic: "Big O Notation", description: "Measuring code efficiency", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["Complexity analysis"], task: "Compare O(n) and O(n^2)." },
        { week: 6, topic: "Search Algos", description: "Binary vs Linear Search", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Optimization"], task: "Search in a sorted list." },
        { week: 7, topic: "Sort Algos", description: "Bubble, Quick, and Merge Sort", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Sorting"], task: "Implement Bubble Sort." },
        { week: 8, topic: "Network Protocols", description: "HTTP, TCP/IP, and MQTT", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["Network literacy"], task: "Explain a 3-way handshake." },
        { week: 9, topic: "Web Servers", description: "Intro to Flask/FastAPI", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Backend dev"], task: "Build a 'Hello' API." },
        { week: 10, topic: "Frontend Basics", description: "HTML/CSS for developers", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Frontend dev"], task: "Style a simple webpage." },
        { week: 11, topic: "Problem Analysis", description: "Breaking real-world issues into components", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Analytical skills"], task: "Solve a neighborhood issue." },
        { week: 12, topic: "Database Intro", description: "SQL and relational data", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["Data management"], task: "Design a schema." },
        { week: 13, topic: "SQL Queries", description: "Select, Insert, Update, Delete", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Querying"], task: "Query a student DB." },
        { week: 14, topic: "Data Processing", description: "Advanced filtering and counting with Python", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["ETL skills"], task: "Process a CSV file." },
        { week: 15, topic: "Pandas Basics", description: "Dataframes and series", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Data science"], task: "Analyze climate data." },
        { week: 16, topic: "Data Cleaning", description: "Handling missing values", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Data quality"], task: "Clean a messy dataset." },
        { week: 17, topic: "Cybersecurity Essentials", description: "Firewalls, VPNs, and Encryption", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["Digital safety"], task: "Set up a mock firewall." },
        { week: 18, topic: "Intro to ML", description: "Regression and predictions", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["ML foundations"], task: "Predict house prices." },
        { week: 19, topic: "Unsupervised Learning", description: "Clustering and patterns", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["Pattern recognition"], task: "Cluster similar products." },
        { week: 20, topic: "AI Ethics", description: "Bias, Fairness, and Transparency", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["Ethical tech"], task: "Debate an AI dilemma." },
        { week: 21, topic: "Natural Language Processing (NLP)", description: "How computers understand text", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["NLP basics"], task: "Explain tokenization." },
        { week: 22, topic: "Sentiment Analysis", description: "Detecting mood in text", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Text analysis"], task: "Analyze 10 movie reviews." },
        { week: 23, topic: "AI Ethics in Depth", description: "Impact of AI on society", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["Social impact"], task: "Write an AI manifesto." },
        { week: 24, topic: "Robotics Logic", description: "Advanced control systems", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["System control"], task: "Code a PID controller." },
        { week: 25, topic: "Pathfinding Algorithms", description: "A* and Dijkstra's algorithm", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["Pathfinding"], task: "Solve a maze on paper." },
        { week: 26, topic: "Decentralized Systems", description: "Blockchain and peer-to-peer", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["Architecture"], task: "Explain a ledger." },
        { week: 27, topic: "Data Encryption", description: "Public and private keys", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Cryptography"], task: "Encrypt a secret message." },
        { week: 28, topic: "Advanced ML Models", description: "Decision trees and forests", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Model selection"], task: "Train a forest model." },
        { week: 29, topic: "Neural Networks concept", description: "Layers, neurons, and weights", type: "Theory", duration: "45 mins", level: "Advanced", outcomes: ["Deep learning"], task: "Draw a simple network." },
        { week: 30, topic: "Graduation Project Design", description: "High-level architecture", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["System architecture"], task: "Submit system diagram." },
        { week: 31, topic: "Architecture Setup", description: "Setting up the tech stack", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Infrastructure"], task: "Initialize Git repo." },
        { week: 32, topic: "Model Development", description: "Training the core AI", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Modeling"], task: "Achieve 80% accuracy." },
        { week: 33, topic: "Frontend Integration", description: "Connecting UI to AI", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Full stack"], task: "Connect API to frontend." },
        { week: 34, topic: "Stress Testing", description: "Testing under heavy load", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Performance"], task: "Run 1000 requests." },
        { week: 35, topic: "Documentation", description: "Writing the user guide", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Technical writing"], task: "Draft a README.md." },
        { week: 36, topic: "Finale Pitch", description: "Final presentation for Grade 8", type: "Practical", duration: "45 mins", level: "Advanced", outcomes: ["Communication"], task: "Pitch to 'investors'." }
    ],
    "Grade 9": [
        { week: 1, topic: "Full Stack Intro", description: "Understanding the entire web stack", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["Stack overview"], task: "Map the tech stack." },
        { week: 2, topic: "Advanced React", description: "Hooks, Context, and State", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Frontend mastery"], task: "Build a stateful app." },
        { week: 3, topic: "Backend Scalability", description: "Microservices and Docker", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["System design"], task: "Containerize an app." },
        { week: 4, topic: "Cloud Deployment", description: "AWS/GCP/Vercel basics", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["DevOps"], task: "Deploy a live site." },
        { week: 5, topic: "Database Tuning", description: "Indexing and Optimization", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Perf tuning"], task: "Optimize a slow query." },
        { week: 6, topic: "CI/CD Pipelines", description: "Automated testing and deployment", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["Workflow automation"], task: "Setup a GitHub Action." },
        { week: 7, topic: "Mobile App Dev", description: "Intro to React Native/Flutter", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Mobile dev"], task: "Build a basic mobile UI." },
        { week: 8, topic: "Real-time Apps", description: "WebSockets and Socket.io", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Real-time tech"], task: "Create a chat app." },
        { week: 9, topic: "Deep Learning Intro", description: "Tensors and Neural Networks", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["DL basics"], task: "Build a simple neuron." },
        { week: 10, topic: "Computer Vision", description: "Object detection and tracking", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Vision AI"], task: "Detect faces in webcam." },
        { week: 11, topic: "Project Ideation", description: "Pitching impactful graduation projects", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Product management"], task: "Pitch your Capstone." },
        { week: 12, topic: "Agile Methodology", description: "Sprints, standups, and backlogs", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["Agile skills"], task: "Plan Sprint 1." },
        { week: 13, topic: "AI + IoT Fusion", description: "Deep integration of models on hardware", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Edge AI"], task: "Run AI on local sensor data." },
        { week: 14, topic: "System Security", description: "Penetration testing and hardening", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Security pro"], task: "Find a site vulnerability." },
        { week: 15, topic: "API Security", description: "JWT, OAuth, and Rate Limiting", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Auth mastery"], task: "Secure your API." },
        { week: 16, topic: "Data Warehousing", description: "Big Data and Analytics", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["Big data"], task: "Design a data warehouse." },
        { week: 17, topic: "Final Capstone Dev", description: "Intensive building phase", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Project execution"], task: "Finish core features." },
        { week: 18, topic: "AI in Finance", description: "Algorithmic trading and fraud detection", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["FinTech basics"], task: "Model a stock trend." },
        { week: 19, topic: "AI in Medicine", description: "Diagnostics and drug discovery", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["HealthTech basics"], task: "Explain AI in X-rays." },
        { week: 20, topic: "Quantum Computing intro", description: "Qubits and superposition", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["Future tech"], task: "Explain a Qubit." },
        { week: 21, topic: "Edge Computing", description: "Processing data near the source", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["Latency reduction"], task: "Sketch edge architecture." },
        { week: 22, topic: "Real-time Data Streams", description: "Kafka and stream processing", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Stream processing"], task: "Build a live tweet wall." },
        { week: 23, topic: "System Optimization", description: "Profiling and bottleneck removal", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Perf engineering"], task: "Speed up a slow app by 2x." },
        { week: 24, topic: "MLOps Basics", description: "Deploying and monitoring ML models", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["MLOps lifecycle"], task: "Design a model pipeline." },
        { week: 25, topic: "Scalable Databases", description: "Sharding and Replication", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["Scalability"], task: "Explain horizontal scaling." },
        { week: 26, topic: "Cloud Architecture (Advanced)", description: "Serverless and Managed Services", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Cloud mastery"], task: "Deploy a serverless API." },
        { week: 27, topic: "Strategic Tech Planning", description: "Roadmapping a product", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["Strategy"], task: "Draft a 12-month roadmap." },
        { week: 28, topic: "Tech Entrepreneurship", description: "Pitching and Fundraising", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["Business skills"], task: "Write a business plan." },
        { week: 29, topic: "Market Analysis for Tech", description: "Understanding competitors", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Market research"], task: "Analyze 3 AI startups." },
        { week: 30, topic: "Capstone Project (In progress)", description: "Refining the graduation project", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Expertise"], task: "Implement user feedback." },
        { week: 31, topic: "Full-stack Integration", description: "Connecting all dots", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Systems integration"], task: "Complete end-to-end flow." },
        { week: 32, topic: "Deployment Strategies", description: "Blue-green and Canary releases", type: "Theory", duration: "45 mins", level: "Pro", outcomes: ["Deployment mastery"], task: "Draft a release plan." },
        { week: 33, topic: "Performance Tuning", description: "Advanced caching and CDN", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Optimization"], task: "Setup a Redis cache." },
        { week: 34, topic: "User Testing & Feedback", description: "Beta testing with real users", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["UAT"], task: "Fix 5 UX issues found." },
        { week: 35, topic: "Final Presentation Prep", description: "Designing the pitch deck", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Presentation skills"], task: "Submit final pitch deck." },
        { week: 36, topic: "Graduation Pitch", description: "Grand finale of the program", type: "Practical", duration: "45 mins", level: "Pro", outcomes: ["Success"], task: "Graduate with honors!" }
    ]
};

if (typeof window !== 'undefined') {
    window.curriculumData = curriculumData;
}
