const mongoose = require('mongoose');

const studentAnswerSchema = new mongoose.Schema({
    questionId: { type: String, required: true },
    answer: { type: String }, // MCQ choice index, code block string, or descriptive answer text
    isCorrect: { type: Boolean }, // Set automatically for MCQs
    score: { type: Number, default: 0 },
    feedback: { type: String } // Feedback comments generated by AI or evaluated by Teacher
});

const examAttemptSchema = new mongoose.Schema({
    id: { type: String, required: true, unique: true },
    examId: { type: String, required: true },
    studentId: { type: String, required: true },
    answers: [studentAnswerSchema],
    score: { type: Number, default: 0 },
    startedAt: { type: Date, default: Date.now },
    submittedAt: { type: Date },
    status: { type: String, enum: ['in-progress', 'submitted', 'evaluated'], default: 'in-progress' },
    
    // Security and monitoring triggers
    securityFlags: {
        tabSwitches: { type: Number, default: 0 },
        fullscreenExits: { type: Number, default: 0 },
        ipAddress: { type: String },
        userAgent: { type: String }
    }
}, {
    timestamps: true
});

examAttemptSchema.index({ examId: 1, studentId: 1 }, { unique: true });

module.exports = mongoose.model('ExamAttempt', examAttemptSchema);
